[package]
name = "zcash_history"
version = "0.3.0"
authors = ["NikVolf <nikvolf@gmail.com>"]
edition = "2021"
rust-version = "1.65"
license = "MIT/Apache-2.0"
documentation = "https://docs.rs/zcash_history/"
description = "Library for Zcash blockchain history tools"
categories = ["cryptography::cryptocurrencies"]

[dev-dependencies]
assert_matches = "1.3.0"
proptest = "1.0.0"

[dependencies]
primitive-types = { version = "0.12", default-features = false }
byteorder = "1"
blake2 = { package = "blake2b_simd", version = "1" }
proptest = { version = "1.0.0", optional = true }

[features]
test-dependencies = ["proptest"]

[lib]
bench = false
