[package]
name = "zcash_client_sqlite"
description = "An SQLite-based Zcash light client"
version = "0.3.0"
authors = [
    "Jack Grigg <jack@z.cash>",
    "Kris Nuttycombe <kris@electriccoin.co>"
]
homepage = "https://github.com/zcash/librustzcash"
repository = "https://github.com/zcash/librustzcash"
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.56.1"

[dependencies]
bech32 = "0.8"
bs58 = { version = "0.4", features = ["check"] }
group = "0.12"
hdwallet = { version = "0.3.1", optional = true }
jubjub = "0.9"
protobuf = "~2.27.1" # MSRV 1.52.1
rand_core = "0.6"
rusqlite = { version = "0.25", features = ["bundled", "time"] }
schemer = "0.2"
schemer-rusqlite = "0.2"
secrecy = "0.8"
time = "0.2"
uuid = "1.1"
zcash_client_backend = { version = "0.5", path = "../zcash_client_backend" }
zcash_primitives = { version = "0.8", path = "../zcash_primitives" }

[dev-dependencies]
proptest = "1.0.0"
regex = "1.4"
tempfile = "3"
zcash_proofs = { version = "0.8", path = "../zcash_proofs" }
zcash_primitives = { version = "0.8", path = "../zcash_primitives", features = ["test-dependencies"] }
zcash_address = { version = "0.2", path = "../components/zcash_address", features = ["test-dependencies"] }

[features]
mainnet = []
test-dependencies = [
    "zcash_primitives/test-dependencies",
    "zcash_client_backend/test-dependencies",
]
transparent-inputs = ["hdwallet", "zcash_client_backend/transparent-inputs"]
unstable = ["zcash_client_backend/unstable"]

[lib]
bench = false
